### ISSUE TITLE
MacOs permissions issue

### ISSUE THREAD

**Issue by samurai71** [alessandromaggio/pythonping#10]
I am trying to use this and it doesn't want to work due to a permissions issue on the mac it needs root permissions to execute the ping command. I am trying to use it in Visual Studio Code. I am running python version 3.7.0. Trying to do this in class at school

**Comment by alessandromaggio** [comment]
Hello! Unfortunately it **needs** root permission, on any OS and not just MacOS. This is because pythonping has to create raw IP packets (instead of TCP/UDP sockets), and this requires root permissions. It is a security constraint of any modern OS.
