### ISSUE TITLE
pythonping-1.0.4.tar.gz: ResponseList has no __iter__ 

### ISSUE THREAD

**Issue by abringenberg** [alessandromaggio/pythonping#24]
The executor.py in pythonping-1.0.4.tar.gz (on gitlab and pypi.org) does not contain the patch of @kysevenle

**Comment by alessandromaggio** [comment]
Moving to version 1.0.5 `__iter__` should be present, starts at line 199.
```python
    def __iter__(self):
        for response in self._responses:
            yield response
```

**Comment by abringenberg** [comment]
Works - thank you!
