### ISSUE TITLE
ModuleNotFoundError: No module named 'pythonping'

### ISSUE THREAD

**Issue by yehudape** [alessandromaggio/pythonping#26]
`$python3 script.py `end with the above error...

system is: ubuntu 18.04. 
Installed via: `$sudo pip install pythonping`.
Successfully installed pythonping-1.0.5

Running: `$sudo pip install pythonping`
result: `Requirement already satisfied: pythonping in ./.local/lib/python2.7/site-packages`

Is pythonping python3 compatible?

Thanks,

**Comment by alessandromaggio** [comment]
Pythonping is written for python 3, and does not support python 2.7.
From your log it looks like you are installing it in the python2.7 folder, so I believe your `pip` command is configured for python 2.7. Try `pip3`.
