### ISSUE TITLE
AttributeError with version 1.06

### ISSUE THREAD

**Issue by IgalKorb** [alessandromaggio/pythonping#33]
Used version 1.0.5 on Mac and linux with python 3.7 with no problem, and now using version 1.0.6 triggers an error on both macOs/ubuntu 16/18 with most simple ping('8.8.8.8'):

`Exception ignored in: <function Communicator.__del__ at 0x7f369f283ee0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pythonping/executor.py", line 260, in __del__
    raise AttributeError("Attribute error because of failed socket init. Make sure you have the root privilege."
AttributeError: Attribute error because of failed socket init. Make sure you have the root privilege. This error may also be caused from DNS resolution problems.`

**Comment by alessandromaggio** [comment]
Fixed in release 1.0.7, already out.
