### ISSUE TITLE
no buffer in ping (v1.0.8)

### ISSUE THREAD

**Issue by eleree** [alessandromaggio/pythonping#34]
Hi All
 I encounted a crash issue as below
**File "site-packages\pythonping\__init__.py", line 53, in ping
  File "site-packages\pythonping\executor.py", line 306, in run
  File "site-packages\pythonping\executor.py", line 277, in listen_for
  File "site-packages\pythonping\network.py", line 52, in receive
OSError: [WinError 10040] A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself**

the ping function works fine at the beginning, but after a long times of ping, it reported no buffer issue? 
How can this happned? And, how to fix it?

Thanks!

**Comment by somervda** [comment]
I ran into this - my fix was to set the BUFFER_SIZE in the network module (socket function ) to be larger. It is currently hard coded to 1024 - I pushed it up to 2048 and could do larger pings, however it would probably be worth setting this dynamically based on the ping size being used. 2000 byte ping worked successfully with the new buffer size and df flag set.

**Comment by alessandromaggio** [comment]
Change suggested by @somervda implemented in release 1.0.9, just published.
Thanks!
