### ISSUE TITLE
Data collision with threading

### ISSUE THREAD

**Issue by deltaflyer4747** [alessandromaggio/pythonping#39]
If i run several threads (threading.Thread) with pings for different hosts, i get mixup of replies, stating impossible times for cerain targets. 

For example i get low response time in local network (which is fine) but then i get similar reply from host on the other side of world. 

Feel free to run test.py script that pings localhost and amazon.com and as you can see in attached screenshot replies from localhost are mixed in amazon thread (and sometimes even with reply seemingly from amazon).

![test](https://user-images.githubusercontent.com/7271362/81286134-df8c5e80-9060-11ea-903b-3a85d87938b1.png)

[test.py](https://github.com/alessandromaggio/pythonping/files/4592469/test.txt)

**Comment by alessandromaggio** [comment]
Yes, at the moment we are not thread-safe. This is because we are sniffing the NIC for incoming replies, and the NIC itself cannot be duplicated in different threads for incoming traffic - that's because there is no way to know to which thread the incoming traffic belongs to.

However, we can implement a workaround to address this issue. We should add some sort of seed/prefix value to use in the ICMP Identifier field to use when we create different threads. In this way, we ensure a given ICMP identifier is created by one thread - and that thread only, and thus we avoid conflicts when replies come back.

**Comment by deltaflyer4747** [comment]
You can specify a pattern in ping. (-p option in linux).

**Comment by alessandromaggio** [comment]
The pattern is not what we are looking for, the pattern is just the payload of the packet and has no say in how replies are reconciled with requests. That's the identifier job (see RFC https://tools.ietf.org/html/rfc792, page 14).

So we only need to have a better way to specify identifiers.

**Comment by deltaflyer4747** [comment]
Ah, identifier. Riiiight ... Well, identifier = os.getpid() is not going to cut it as threads are not processes, right...

then something as simple as 

    try:
        identifier = threading.get_ident()
    except Exception:
        identifier = os.getpid()

will do the trick (tested, works). Feel free to modify conditioning to your own likings ;)

**Comment by deltaflyer4747** [comment]
I tested this patch and works for me:

`--- icmp.py_orig        2020-05-11 00:27:06.437013303 +0200
+++ icmp.py     2020-05-11 00:26:56.168855981 +0200
@@ -3,6 +3,7 @@
 import struct
 import select
 import time
+import threading


 def checksum(data):
@@ -150,7 +151,7 @@
             payload = bytes(payload, 'utf8')
         self.payload = payload
         if identifier is None:
-            identifier = os.getpid()
+            identifier = threading.get_ident()
         self.id = identifier & 0xFFFF           # Prevent identifiers bigger than 16 bits
         self.sequence_number = sequence_number
         self.received_checksum = None


--- executor.py_orig    2020-05-11 00:26:47.004715567 +0200
+++ executor.py 2020-05-11 00:26:27.604418296 +0200
@@ -4,6 +4,7 @@
 import sys
 from . import icmp
 from . import network
+import threading

 # Python 3.5 compatibility
 if sys.version_info[1] == 5:
@@ -242,7 +243,7 @@
         self.responses = ResponseList(verbose=verbose, output=output)
         self.seed_id = seed_id
         if self.seed_id is None:
-            self.seed_id = os.getpid() & 0xFFFF
+            self.seed_id = threading.get_ident() & 0xFFFF

     def __del__(self):
         pass
`

**Comment by alessandromaggio** [comment]
You can make a pull request with that and we will integrate it in the next release.

**Comment by malbers15** [comment]
I just encountered this issue myself.  I also noticed that this person found a possible fix by randomizing the seed_id:
https://github.com/alessandromaggio/pythonping/issues/41

Is there an ETA on a pull request for this issue?  Or is work still being done?

**Comment by deltaflyer4747** [comment]
yes, i ended up using random as well. 
            identifier = random.randrange(65535)
and
            self.seed_id = random.randrange(65535) & 0xFFFF

**Comment by malbers15** [comment]
@deltaflyer4747 I can see why you moved away from threading.get_ident() after testing myself.  I concur; replacing os.getpid() with  random.randrange(65535) seems to be the best solution.  Perhaps the following to be more explicit?

`random.randint(0x1, 0xFFFF) & 0xFFFF`

**Comment by malbers15** [comment]
@deltaflyer4747 is the identifier change in the following necessary?
`class ICMP:
    LEN_TO_PAYLOAD = 41     # Ethernet, IP and ICMP header lengths combined

    def __init__(self, message_type=Types.EchoReply, payload=None, identifier=None, sequence_number=1):
        """Creates an ICMP packet

        :param message_type: Type of ICMP message to send
        :type message_type: Union[ICMPType, (int, int), int]
        :param payload: utf8 string or bytes payload
        :type payload: Union[str, bytes]
        :param identifier: ID of this ICMP packet
        :type identifier: int"""
        self.message_code = 0
        if issubclass(message_type, ICMPType):
            self.message_type = message_type.type_id
        elif isinstance(message_type, tuple):
            self.message_type = message_type[0]
            self.message_code = message_type[1]
        elif isinstance(message_type, int):
            self.message_type = message_type
        if payload is None:
            payload = bytes('1', 'utf8')
        elif isinstance(payload, str):
            payload = bytes(payload, 'utf8')
        self.payload = payload
        if identifier is None:
            identifier = os.getpid()
        self.id = identifier & 0xFFFF           # Prevent identifiers bigger than 16 bits
        self.sequence_number = sequence_number
        self.received_checksum = None`

**Comment by malbers15** [comment]
@deltaflyer4747 ?

**Comment by malbers15** [comment]
@deltaflyer4747 
so, this may be a little overkill, but I figured, better to protect the main thread in the very unlikely chance that random picked the same one, so how about this:
`from threading import main_thread, current_thread`

`            if self.seed_id is None:`
`                self.seed_id = getpid() & 0xFFFF`
`                if current_thread() is not main_thread():`
`                    while True:`
`                        new_seed_id = randint(0x1, 0xFFFF)`
`                        if new_seed_id != self.seed_id:`
`                            self.seed_id = new_seed_id`
`                            break`

I also looked into it and can see identifier does not need to change since in the case of a ping, the ICMP class used for reply is using the seed_id from the request to set the identifier

**Comment by malbers15** [comment]
@alessandromaggio @deltaflyer4747 
https://github.com/alessandromaggio/pythonping/pull/42

I have put it all together in a pull request, as well as an option for payload matching (maintains default behaviour).

**Comment by alessandromaggio** [comment]
@malbers15 

Thank you for the PR. I have created the `thread-safe` branch to test it and integrate it properly. Hope to release the fix in the next days.

**Comment by malbers15** [comment]
@alessandromaggio no problem happy to help!  Please see my recent pull request to your thread-safe branch as I forgot to the inverse test case for payload match (covers windows/legacy behaviour with google DNS A truncated reply test case).

**Comment by alessandromaggio** [comment]
Changes integrated into v1.0.11, out now. Thanks @malbers15.

**Comment by malbers15** [comment]
@alessandromaggio 
please review and merge these bugs ASAP as I have worked quickly to fix them and don't want a buggy version of mutithreading or match to be out there for too long:
https://github.com/alessandromaggio/pythonping/issues/48

https://github.com/alessandromaggio/pythonping/pull/49
