### ISSUE TITLE
Bug in match code on made from wrong assumptions based on misleading documentation, update documentation to reflect Union of string and bytes as payload input internally, and Linux legacy match off case in threaded scenario broken

### ISSUE THREAD

**Issue by malbers15** [alessandromaggio/pythonping#48]
**Describe the bug**
-I mistakenly compared strings and bytes in my match code based on false assumptions in the library where bytes was stated as the input in a few places, when it should have been documented as Union input of strings or bytes.  Default behavior is to use the random_text function to generate the payload, which returns a string.  I had used bytes manually in some of my test code and did not account for the default strings case.

-Linux legacy match off case in threaded scenario broken due to the way sockets are handled on linux and the incorrect copying of payload/in wrong place

**To Reproduce**
-match code off (legacy usage, default) 
-turn match on for any ping, all will fail

**Expected behavior**
-linux legacy usage with multithreading should not mark as timed out when response received
-only those servers that truncate a large reply should fail with match on, such as google DNS A

**Desktop (please complete the following information):**
 - OS: Any

**Comment by malbers15** [comment]
@alessandromaggio 

My bad.  It is fixed in the PR:
https://github.com/alessandromaggio/pythonping/pull/49

**Comment by alessandromaggio** [comment]
Thank you for the quick fix @malbers15, integrated in v1.0.12 being released now.
