### ISSUE TITLE
Raspberry Pi import error

### ISSUE THREAD

**Issue by relwin** [alessandromaggio/pythonping#50]
**Describe the bug**
File "/home/pi/.local/lib/python3.5/site-packages/pythonping/__init__.py", line 9
    SEED_IDs: List[int] = []
            ^
SyntaxError: invalid syntax

...and:
File "pingsimple.py", line 1, in <module>
    from pythonping import ping
  File "/home/pi/.local/lib/python2.7/site-packages/pythonping/__init__.py", line 9
    SEED_IDs: List[int] = []
            ^
SyntaxError: invalid syntax

**To Reproduce**
python3 -V
Python 3.5.3
pythonping-1.0.12

Simple python script, or manually run interpreter:
>from pythonping import ping

**Expected behavior**
import correctly.

**Screenshots**
See description.

**Desktop (please complete the following information):**
Raspberry Pi 3 Model B Plus Rev 1.3
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Additional context**
Works properly with Win10 python 3.8
Works properly with Ubuntu python 3.6

**Comment by malbers15** [comment]
This is reproducible with any OS version of python 3.5 I just verified.  I will make a PR addressing this.

However for the python 2.7 attempt, python2 is officially deprecated as of 1/1/2020, and also, typing isn't supported in python2 lines:
https://www.python.org/doc/sunset-python-2/

**Comment by malbers15** [comment]
Fixed here, please review @alessandromaggio 

https://github.com/alessandromaggio/pythonping/pull/52

**Comment by malbers15** [comment]
Changes have been merged to master and this issue can be closed

**Comment by relwin** [comment]
installed pythonping-1.0.12
executes properly on the Pi platform.
