### ISSUE TITLE
ping through interface 

### ISSUE THREAD

**Issue by ArcherSking10** [alessandromaggio/pythonping#68]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alessandromaggio** [comment]
I am sorry, you provided no description on this request. Please, re-open accordingly and provide documentation.
If I get it right, I think you are looking for the -l option for which we already have a PR going, but I may be wrong. Fill the form correctly and we will see what to do about it.

Thanks in advance!
