### ISSUE TITLE
Do pythonping Support for PY2

### ISSUE THREAD

**Issue by throwbear** [alessandromaggio/pythonping#79]
when I tried to import pythonping in python2.7.18
I got this error：
![image](https://user-images.githubusercontent.com/8360116/158100931-73ce7a4f-eb3c-4946-ba5b-c05b84d9df48.png)

**Comment by alessandromaggio** [comment]
Python Ping supports only Python 3.x.
As Python 2.7 is a legacy platform there is no plan of supporting it in the future. My apologies, but you will have to upgrade to Python 3.
